export const CategoriesActionTypes = {
	FETCH_CATEGORIES_COLLECTION_START: 'FETCH_CATEGORIES_COLLECTION_START',
	FETCH_CATEGORIES_COLLECTION_SUCCESS: 'FETCH_CATEGORIES_COLLECTION_SUCCESS',
	FETCH_CATEGORIES_COLLECTION_FAILURE: 'FETCH_CATEGORIES_COLLECTION_FAILURE',
	CLEAR_CATEGORIES_COLLECTION: 'CLEAR_CATEGORIES_COLLECTION',
};
