export const UsersActionTypes = {
	FETCH_USERS_COLLECTION_START: 'FETCH_USERS_COLLECTION_START',
	FETCH_USERS_COLLECTION_SUCCESS: 'FETCH_USERS_COLLECTION_SUCCESS',
	FETCH_USERS_COLLECTION_FAILURE: 'FETCH_USERS_COLLECTION_FAILURE',
	CLEAR_USERS_COLLECTION: 'CLEAR_USERS_COLLECTION',
};
